### ISSUE TITLE
Error running command: Build script returned non-zero exit code: 1

### ISSUE THREAD

**Issue by orx57** [netlify-templates/cactus-base#2]
**Description of problem:**
Build fail when deploying this template with "Deploy to Netlify" button from staticgen.com.

**Expected:**
Build successful.

**Traceback:**
```shell
11:36:51 AM:     Complete output from command python setup.py egg_info:
11:36:51 AM:     Traceback (most recent call last):
11:36:51 AM:       File "<string>", line 1, in <module>
11:36:51 AM:       File "/tmp/pip-install-bFMX4R/tornado/setup.py", line 146, in <module>
11:36:51 AM:         raise ImportError("Tornado requires an up-to-date SSL module. This means "
11:36:51 AM:     ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).
11:36:51 AM:     ----------------------------------------
11:36:51 AM: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-bFMX4R/tornado/
11:36:51 AM: /opt/buildhome/python2.7/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
11:36:51 AM:   InsecurePlatformWarning
11:36:51 AM: You are using pip version 18.1, however version 19.0.3 is available.
11:36:51 AM: You should consider upgrading via the 'pip install --upgrade pip' command.
11:36:51 AM: Error installing pip dependencies
11:36:51 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
11:36:51 AM: Error running command: Build script returned non-zero exit code: 1
11:36:51 AM: Failing build: Failed to build site
```
I attach the complete [build.log](https://github.com/netlify-templates/cactus-base/files/2947486/build.log).

**Additional info:**
I have try to add a `runtime.txt` file to use python 3.4+ or add `tornado>=4.0.0,<5.0.0` to `requirements.txt` without success.

**Comment by orx57** [comment]
Close this issue because it has been unfortunately stalled for too long with no activity.
